[package]
name = "dvf"
version = "1.4.0"
authors = ["Zico <zhicong303@gmail.com", "Will <jianliiin96@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["slasher-lmdb"]
# Compiles the BLS crypto code so that the binary is portable across machines.
portable = ["bls/supranational-portable"]
# Compiles BLST so that it always uses ADX instructions.
modern = ["bls/supranational-force-adx"]
# Support minimal spec (used for testing only).
spec-minimal = []
# Support Gnosis spec and Gnosis Beacon Chain.
gnosis = []
# Support slasher MDBX backend.
slasher-mdbx = ["slasher/mdbx"]
# Support slasher LMDB backend.
slasher-lmdb = ["slasher/lmdb"]
# Support slasher redb backend.
slasher-redb = ["slasher/redb"]
# Deprecated. This is now enabled by default on non windows targets.
jemalloc = []

[target.'cfg(not(target_os = "windows"))'.dependencies]
malloc_utils = { path = "lighthouse/common/malloc_utils", features = ["jemalloc"] }

[target.'cfg(target_os = "windows")'.dependencies]
malloc_utils = { path = "lighthouse/common/malloc_utils" }

[dependencies]
slog = { version = "2", features = ["max_level_debug", "release_max_level_debug", "nested-values"] }
types = { path = "lighthouse/consensus/types" }
bls = { path = "lighthouse/crypto/bls" }
ethereum_hashing = "0.7.0"
clap = { version = "4.5.4", features = ["derive", "cargo", "wrap_help"] }
environment = { path = "lighthouse/lighthouse/environment" }
futures = "0.3"
validator_client = { path = "lighthouse/validator_client" }
clap_utils = { path = "lighthouse/common/clap_utils" }
eth2_network_config = { path = "lighthouse/common/eth2_network_config" }
lighthouse_version = { path = "lighthouse/common/lighthouse_version" }
account_utils = { path = "lighthouse/common/account_utils" }
metrics = { path = "lighthouse/common/metrics" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
task_executor = { path = "lighthouse/common/task_executor" }
malloc_utils = { path = "lighthouse/common/malloc_utils" }
directory = { path = "lighthouse/common/directory" }
unused_port = { path = "lighthouse/common/unused_port" }
slasher = { path = "lighthouse/slasher", default-features = false }
logging = { path = "lighthouse/common/logging" }
boot_node = { path = "src/boot_node" }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "signal", "macros"] }

[dev-dependencies]
tempfile = "3"
validator_dir = { path = "lighthouse/common/validator_dir" }
slashing_protection = { path = "lighthouse/validator_client/slashing_protection" }
lighthouse_network = { path = "lighthouse/beacon_node/lighthouse_network" }
sensitive_url = { path = "lighthouse/common/sensitive_url" }
eth1 = { path = "lighthouse/beacon_node/eth1" }
eth2 = { path = "lighthouse/common/eth2" }
beacon_processor = { path = "lighthouse/beacon_node/beacon_processor" }
beacon_node_fallback = { path = "lighthouse/validator_client/beacon_node_fallback" }
initialized_validators = { path = "lighthouse/validator_client/initialized_validators" }


[[test]]
name = "lighthouse_tests"
path = "tests/main.rs"

# Prevent cargo-udeps from flagging the dummy package `target_check`, which exists only
# to assert properties of the compilation target.
[package.metadata.cargo-udeps.ignore]
normal = ["target_check"]
