#!/bin/bash
START_PRO=$1
NODE_IP=`curl -s ifconfig.me`

if [[ "$START_PRO" == "boot" ]]; then
  /usr/local/bin/dvf_root_node $NODE_IP 9005 2>&1
elif [[ -n "$START_PRO" && "$START_PRO" != "boot" ]]; then
  /usr/local/bin/dvf validator_client \
    --debug-level info \
    --network prater \
    --beacon-nodes http://127.0.0.1:5052 \
    --api https://api-goerli-dev.safestake.xyz/v1/collect_performance \
    --ws-url wss://goerli.infura.io/ws/v3/d9ebf3b4bf724231a9793aa84b9fe2c3 \
    --contract-address 93Ec63F53Fd7362CEAb5A70F1c1B1BD5B49eeb81 \
    --ip $NODE_IP \
    --boot-enr $START_PRO 2>&1
else
  echo "Please input first argument(boot or enr) !"
  exit 1
fi