services:
  dvf_root_node:
    network_mode: "host"
    image: parastate/dvf-operator:${IMAGE_TAG}
    pull_policy: always
    command:
      - /bin/sh
      - -c
      - |
        dvf boot_node --ip ${NODE_IP} --port 9005 2>&1
    expose:
      - "9005"
    volumes:
      - boot-data:/root/.lighthouse
volumes:
  boot-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/boot
