[package]
name = "consensus"
version = "0.1.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>"]
edition = "2018"
publish = false

[dependencies]
thiserror = "1.0.21"
tokio = { version = "1.3.0", features = ["rt", "time", "macros", "sync"] }
ed25519-dalek = "2.1.1"
log = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.0.1"
bincode = "1.3.1"
futures = "0.3.8"
async-recursion = "0.3.1"
base64 = "0.13.0"
async-trait = "0.1.50"
exit-future = "0.2.0"
store = { path = "../store" }
crypto = { path = "../crypto" }
network = { path = "../network" }
mempool = { path = "../mempool" }
utils = { path = "../utils" }

[dev-dependencies]
tokio-util = { version = "0.6.2", features= ["codec"] }
rand = "0.7.3"

[features]
benchmark = []
